build time -- 01:24:44
running test
Failure: FileNotFoundError ([Errno 2] No such file or directory: '') ... ERROR

======================================================================
ERROR: Failure: FileNotFoundError ([Errno 2] No such file or directory: '')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/mark.potts/.local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/u/mark.potts/.local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/u/mark.potts/.local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/u/mark.potts/.local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/lfs/h1/emc/ptmp/Mark.Potts/gfortran_10.3.0_mpi_g_develop/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/lfs/h1/emc/ptmp/Mark.Potts/gfortran_10.3.0_mpi_g_develop/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/lfs/h1/emc/ptmp/Mark.Potts/gfortran_10.3.0_mpi_g_develop/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/lfs/h1/emc/ptmp/Mark.Potts/gfortran_10.3.0_mpi_g_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 36, in <module>
    with open(esmfmk, 'r') as MKFILE:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
XML: /lfs/h1/emc/ptmp/Mark.Potts/gfortran_10.3.0_mpi_g_develop/src/addon/ESMPy/nosetests.xml
----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vs', '--with-xunit', '-a', '!slow,!parallel', 'src/ESMF']' returned non-zero exit status 1.
